### ISSUE TITLE
有代码示例吗

### ISSUE THREAD

**Issue by 4379711** [penghaiping/selling-partner-sdk#1]
能不能看一下你的代码示例,不知道怎么使用.

**Comment by penghaiping** [comment]
具体的使用方式https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md 在这里有说明怎么调用，我周末找个时间写个demo model

**Comment by penghaiping** [comment]
> 能不能看一下你的代码示例,不知道怎么使用.

具体的使用方式https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md 在这里有说明怎么调用，我周末找个时间写个demo model

**Comment by 4379711** [comment]
> > 能不能看一下你的代码示例,不知道怎么使用.
> 
> 具体的使用方式https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md 在这里有说明怎么调用，我周末找个时间写个demo model

亚马逊文档我看了,只有授权和认证部分,就等你的demo了,不用写很多,写一个demo就可以了,不然都不知道先new什么再new什么,
你有没有联系方式,或者交流群之类的,有个业务问题想请教一下

**Comment by penghaiping** [comment]
> > > 能不能看一下你的代码示例,不知道怎么使用.
> > 
> > 
> > 具体的使用方式https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md 在这里有说明怎么调用，我周末找个时间写个demo model
> 
> 亚马逊文档我看了,只有授权和认证部分,就等你的demo了,不用写很多,写一个demo就可以了,不然都不知道先new什么再new什么,
> 你有没有联系方式,或者交流群之类的,有个业务问题想请教一下

写了个SellerApi调用的demo，请看sellingpartner-sellers-api/src/test/java/com/amazon/spapi/sellers/api/SellersApiTest.java
