### ISSUE TITLE
能给个联系方式么

### ISSUE THREAD

**Issue by ClockworkBunni** [penghaiping/selling-partner-sdk#2]
能给个联系方式么？我们可能需要您的协助，有偿

**Comment by penghaiping** [comment]
> 能给个联系方式么？我们可能需要您的协助，有偿

请邮件联系我，谢谢

**Comment by the-Rings** [comment]
我也需要你的帮助，想请你喝杯咖啡，但是没法给你

**Comment by penghaiping** [comment]
> 我也需要你的帮助，想请你喝杯咖啡，但是没法给你

哈哈，readme中有支付宝微信收款码，邮箱penghaiping1001@163.com也可联系

**Comment by the-Rings** [comment]
刚刚我请你喝了一杯咖啡

**Comment by the-Rings** [comment]
这个项目是不是有使用指南呢？我没有找到

**Comment by penghaiping** [comment]
> 刚刚我请你喝了一杯咖啡

谢谢！

**Comment by penghaiping** [comment]
> 这个项目是不是有使用指南呢？我没有找到

目前没有写，请结合https://github.com/amzn/selling-partner-api-docs 文档来获得使用api的方式
