### ISSUE TITLE
shipping 这个接口的所有子接口一直给500错误

### ISSUE THREAD

**Issue by 4379711** [penghaiping/selling-partner-sdk#3]
是那里不对吗?

**Comment by 4379711** [comment]
另外,我在[这里](https://github.com/amzn/selling-partner-api-models/issues/1007)提交了Issues,里面有详细参数描述

**Comment by penghaiping** [comment]
> 另外,我在[这里](https://github.com/amzn/selling-partner-api-models/issues/1007)提交了Issues,里面有详细参数描述

邮件联系我，把你的代码发我看下，估计是你endpoint或region配置错了
