### ISSUE TITLE
关于产品上传到amazon

### ISSUE THREAD

**Issue by weiliguo15634145** [penghaiping/selling-partner-sdk#4]
请教一下 , 产品信息刊登到amazon 是feeds-api 吗 ? Product.xsd 是用来做什么的 , 能生成产品信息的实体类吗 ?

**Comment by penghaiping** [comment]
> 请教一下 , 产品信息刊登到amazon 是feeds-api 吗 ? Product.xsd 是用来做什么的 , 能生成产品信息的实体类吗 ?

是的，xsd是生成xml的定义文件，你可以将xsd转换成java类操作生成xml文件上传给amazon后调用createFeed接口做product inventory等catagroy管理

**Comment by weiliguo15634145** [comment]
我看Product中的ProductData是类目的信息 , 这些信息怎么赋值 ? 不同的类目都是JavaBean

**Comment by weiliguo15634145** [comment]
还有一个疑惑 , 产品 , 产品图片 , 产品价格 , 产品库存 和产品变种关系是不同的feed , 也就是上传一个有变种的产品至少要提交5个feed 是吗? 文档建议20分钟内只能提交一个同种类型的feed , 那么如果我多个产品提交一个feed , 会不会有其中某个产品上传失败的情况 , 或者 有没有产品图片上传成功 , 产品价格上传失败的情况?

**Comment by penghaiping** [comment]
> 我看Product中的ProductData是类目的信息 , 这些信息怎么赋值 ? 不同的类目都是JavaBean

这个在amazon后台的help里有对xsd的说明

**Comment by penghaiping** [comment]
> 还有一个疑惑 , 产品 , 产品图片 , 产品价格 , 产品库存 和产品变种关系是不同的feed , 也就是上传一个有变种的产品至少要提交5个feed 是吗? 文档建议20分钟内只能提交一个同种类型的feed , 那么如果我多个产品提交一个feed , 会不会有其中某个产品上传失败的情况 , 或者 有没有产品图片上传成功 , 产品价格上传失败的情况?

是的，5种feedType，他们都是分开做的，所以会出现产品上传成功，但是图片未成功。具体读文档吧，仔细阅读文档
